
export enum ThemeMode {
  LIGHT = 'LIGHT',
  DARK = 'DARK',
  COLORFUL = 'COLORFUL',
  CUSTOM = 'CUSTOM'
}

export enum AppMode {
  ORACLE = 'ORACLE',
  IMAGE = 'IMAGE',
  EDITOR = 'EDITOR',
  EXCEL = 'EXCEL',
  WORD = 'WORD',
  POWER_POINT = 'POWER_POINT',
  GAMES = 'GAMES',
  PROJECT_MAKER = 'PROJECT_MAKER',
  ARCHITECT = 'ARCHITECT',
  PYTHON = 'PYTHON',
  BANNER_CREATOR = 'BANNER_CREATOR',
  COUNTRY_INFORMER = 'COUNTRY_INFORMER',
  LOGO_INVENTOR = 'LOGO_INVENTOR',
  EXAM = 'EXAM',
  DICTIONARY = 'DICTIONARY',
  TRANSLATOR = 'TRANSLATOR',
  VIDEO_GEN = 'VIDEO_GEN',
  HISTORY = 'HISTORY',
  THEMES = 'THEMES',
  PERFORMANCE = 'PERFORMANCE',
  COSMIC_CERTIFICATE = 'COSMIC_CERTIFICATE',
  COSMIC_WATCH = 'COSMIC_WATCH'
}

export enum View {
  CHAT = 'CHAT',
  GAME_ZONE = 'GAME_ZONE',
  TRANSLATOR = 'TRANSLATOR',
  DICTIONARY = 'DICTIONARY',
  COSMIC_POWER_POINT = 'COSMIC_POWER_POINT',
  PLAYSTORE = 'PLAYSTORE',
  COSMIC_LINK = 'COSMIC_LINK',
  PROJECT_MAKER = 'PROJECT_MAKER',
  YOUTUBE = 'YOUTUBE',
  COUNTRY_INTEL = 'COUNTRY_INTEL',
  COSMIC_PAPER_GEN = 'COSMIC_PAPER_GEN',
  IMAGE_GEN = 'IMAGE_GEN',
  VIDEO_GEN = 'VIDEO_GEN',
  COSMIC_WATCH = 'COSMIC_WATCH',
  COSMIC_WORD = 'COSMIC_WORD',
  COSMIC_EXCEL = 'COSMIC_EXCEL',
  HISTORY = 'HISTORY',
  PYTHON = 'PYTHON',
  BANNER_GEN = 'BANNER_GEN',
  THEMES = 'THEMES',
  PERFORMANCE = 'PERFORMANCE',
  COSMIC_CERTIFICATE = 'COSMIC_CERTIFICATE'
}

export enum TaskMode {
  GENERAL = 'GENERAL',
  TRANSLATOR = 'TRANSLATOR',
  DICTIONARY = 'DICTIONARY',
  COSMIC_POWER_POINT = 'COSMIC_POWER_POINT',
  COUNTRY_INTEL = 'COUNTRY_INTEL',
  COSMIC_PAPER_GEN = 'COSMIC_PAPER_GEN',
  IMAGE_GEN = 'IMAGE_GEN',
  VIDEO_GEN = 'VIDEO_GEN',
  COSMIC_WATCH = 'COSMIC_WATCH',
  COSMIC_WORD = 'COSMIC_WORD',
  COSMIC_EXCEL = 'COSMIC_EXCEL',
  HISTORY = 'HISTORY',
  PYTHON = 'PYTHON',
  BANNER_GEN = 'BANNER_GEN',
  THEMES = 'THEMES',
  PERFORMANCE = 'PERFORMANCE',
  COSMIC_CERTIFICATE = 'COSMIC_CERTIFICATE'
}

export type AppState = 'LOCK' | 'HOME' | 'CHAT' | 'GAMES' | 'TRANSLATOR' | 'DICTIONARY' | 'COSMIC_POWER_POINT' | 'PLAYSTORE' | 'COSMIC_LINK' | 'PROJECT_MAKER' | 'YOUTUBE' | 'COUNTRY_INTEL' | 'QUESTION_PAPER' | 'IMAGE_GEN' | 'VIDEO_GEN' | 'COSMIC_WATCH' | 'COSMIC_WORD' | 'COSMIC_EXCEL' | 'HISTORY' | 'PYTHON' | 'BANNER_GEN' | 'THEMES' | 'PERFORMANCE' | 'COSMIC_CERTIFICATE';

export interface BannerSection {
  heading: string;
  points: string[];
}

export interface BannerData {
  title: string;
  subtitle: string;
  sections: BannerSection[];
  gradient: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  type?: 'text' | 'image' | 'video' | 'data' | 'banner';
  mediaUrl?: string;
  bannerData?: BannerData;
}
